get_kernel:
	cd kernel.git; \
	cp ../patches/Makefile ./arch/arm64/boot/dts/rockchip/; \
	git init; \
	git add * ; \
	git commit -m "initial release"; \
	git status; \
	git remote add origin https://github.com/FireflyTeam/kernel.git
