get_kernel:
	cd debian_kernel.git; \
	cp ../patches/gcc-wrapper.py ./scripts/; \
	git init; \
	git add * ; \
	git commit -m "initial release"; \
	git status; \
	git remote add origin https://github.com/TinkerBoard/debian_kernel.git 
